sonar.projectKey=Midtown-Technology-Group_weekly-review
sonar.organization=mtg-thomas
sonar.sources=.
sonar.exclusions=**/.venv/**,**/venv/**,**/__pycache__/**,**/.pytest_cache/**,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.python.version=3.11
